apiVersion: v1
kind: Service
metadata:
  name: {{ include "passage.fullname" . }}
  labels:
    {{- include "passage.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: minecraft
      protocol: TCP
      name: minecraft
  selector:
    {{- include "passage.selectorLabels" . | nindent 4 }}
