[package]
name = "passage-core"
description = "Minecraft Protocol Toolkit"
authors = [
    "Joshua Dean Küpper <admin@joshua-kuepper.de>",
    "Paul Wagner <contact@paulwagner.dev>",
]
license = "MIT"
readme = "../README.md"
keywords = ["minecraft", "opentelemetry", "monitoring", "package"]
categories = ["emulators", "network-programming"]
version.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
bytestring = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros", "net", "io-util"] }
tokio-util = { workspace = true, features = ["codec", "rt"] }
tracing = { workspace = true, features = ["std", "attributes"] }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
fastnbt = { workspace = true }
num-bigint = { workspace = true }
sha1 = { workspace = true }
aes = { workspace = true }
cfb8 = { workspace = true }
opentelemetry = { workspace = true }
schemars = { workspace = true, features = ["default", "uuid1"], optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "test-util", "sync"] }
tracing-subscriber = { workspace = true }

[features]
config-schema = ["dep:schemars"]
