[package]
name = "passage-core"
version.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros", "net"] }
tokio-util = { workspace = true, features = ["codec", "rt"] }
tracing = { workspace = true, features = ["default"] }
