[package]
name = "passage-core"
version.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "macros", "net", "io-util"] }
tokio-util = { workspace = true, features = ["codec", "rt"] }
tracing = { workspace = true, features = ["std", "attributes"] }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
fastnbt = { workspace = true }
num-bigint = { workspace = true }
sha1 = { workspace = true }
opentelemetry = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "test-util", "sync"] }
tracing-subscriber = { workspace = true }
