//! Packet identity and the declarative packet definition macro.
//!
//! A packet type is declared **once** and carries its own version mapping. Both directions of the
//! mapping are derived from that single declaration:
//!
//! * *encode*: [`Packet::id`] resolves the ID for the connection's version, so no call site ever
//!   writes a literal ID.
//! * *decode*: [`Router`](crate::router::Router) builds a `(phase, id) -> handler` table by asking
//!   every registered packet for its ID at the negotiated version.
//!
//! That removes the duplication of the previous design, where a `const ID` on the packet and a
//! `match` in the dispatcher both had to be kept in sync.

use crate::error::{Error, InternalError, Result};
use crate::version::{Feature, ProtocolVersion};
use crate::wire::{Reader, Wire, Writer};

/// The protocol phase a packet belongs to.
///
/// The phase is part of a packet's identity: IDs are only unique within a phase and direction.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Phase {
    /// Before the handshake has been processed.
    Handshake,
    /// Server list ping.
    Status,
    /// Login and encryption.
    Login,
    /// Configuration, including resource packs, cookies and the transfer packet.
    Configuration,
    /// In-game. Passage never reaches this phase, but the driver is not Passage.
    Play,
}

impl Phase {
    /// The number of phases, for table sizing.
    pub const COUNT: usize = 5;

    /// A dense index for table lookups.
    #[must_use]
    pub const fn index(self) -> usize {
        match self {
            Phase::Handshake => 0,
            Phase::Status => 1,
            Phase::Login => 2,
            Phase::Configuration => 3,
            Phase::Play => 4,
        }
    }

    /// Reconstructs a phase from its [`Phase::index`].
    #[must_use]
    pub const fn from_index(index: usize) -> Option<Self> {
        match index {
            0 => Some(Phase::Handshake),
            1 => Some(Phase::Status),
            2 => Some(Phase::Login),
            3 => Some(Phase::Configuration),
            4 => Some(Phase::Play),
            _ => None,
        }
    }
}

/// Which way a packet travels.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Direction {
    /// Client to server.
    Serverbound,
    /// Server to client.
    Clientbound,
}

impl Direction {
    /// The opposite direction.
    #[must_use]
    pub const fn flip(self) -> Self {
        match self {
            Direction::Serverbound => Direction::Clientbound,
            Direction::Clientbound => Direction::Serverbound,
        }
    }
}

/// A protocol packet.
///
/// Implementations are normally generated by [`packet!`](crate::packet!).
pub trait Packet: Sized + Send + Sync + 'static {
    /// The name of the packet, used for tracing, metrics and error messages.
    const NAME: &'static str;

    /// The phase this packet belongs to.
    const PHASE: Phase;

    /// The direction this packet travels in.
    const DIRECTION: Direction;

    /// The packet ID in the given protocol version, or [`None`] if the packet does not exist there.
    fn id(version: ProtocolVersion) -> Option<i32>;

    /// Decodes the packet payload (without length prefix and ID).
    fn decode(reader: &mut Reader<'_>, version: ProtocolVersion) -> Result<Self>;

    /// Encodes the packet payload (without length prefix and ID).
    fn encode(&self, writer: &mut Writer<'_>, version: ProtocolVersion) -> Result<()>;
}

/// Reads a field that only exists once `feature` is available.
///
/// Absent fields decode to [`None`] instead of failing, so one struct serves every version.
pub fn read_since<T: Wire>(
    reader: &mut Reader<'_>,
    version: ProtocolVersion,
    feature: Feature,
    field: &'static str,
) -> Result<Option<T>> {
    if version.has(feature) {
        Ok(Some(T::read(reader, version, field)?))
    } else {
        Ok(None)
    }
}

/// Writes a field that only exists once `feature` is available.
///
/// If the version requires the field but it is unset, this fails instead of writing a default.
/// Emitting a truncated packet would desynchronise the client with no way to diagnose it, so this
/// is the one place where the driver is deliberately strict about *our* mistakes.
pub fn write_since<T: Wire>(
    writer: &mut Writer<'_>,
    version: ProtocolVersion,
    value: &Option<T>,
    feature: Feature,
    packet: &'static str,
    field: &'static str,
) -> Result<()> {
    match (version.has(feature), value) {
        (true, Some(value)) => {
            value.write(writer, version);
            Ok(())
        }
        (true, None) => Err(Error::Internal(InternalError::MissingField {
            packet,
            field,
            version,
        })),
        // The field does not exist on the wire for this version: dropping it is correct.
        (false, _) => Ok(()),
    }
}

/// Declares a packet: its fields, its phase and direction, and its ID per protocol version.
///
/// # Syntax
///
/// ```ignore
/// packet! {
///     /// The `Login Success` packet.
///     pub struct LoginSuccess {
///         /// The authenticated profile id.
///         pub user_id: Uuid,
///         /// The session id. Only on the wire since the 26.2 protocol.
///         pub session_id: Option<Uuid> = since(LoginSuccessSessionId),
///     }
///     phase = Login;
///     direction = Clientbound;
///     ids = [ versions::V1_20_5 => 0x02 ];
/// }
/// ```
///
/// `ids` is a list of `first_version => id`, **ordered from newest to oldest**. The first entry
/// whose version is `<=` the connection's version wins; if none matches, the packet does not exist
/// in that version and [`Packet::id`] returns [`None`].
///
/// `= since(Feature)` marks a field that older versions do not have. Its type must be
/// `Option<T>`: [`None`] means "not on the wire", which is what every version below the gate
/// decodes to.
#[macro_export]
macro_rules! packet {
    (
        $(#[$meta:meta])*
        pub struct $name:ident {
            $(
                $(#[$field_meta:meta])*
                pub $field:ident : $field_ty:ty $(= since($feature:ident))?
            ),* $(,)?
        }
        phase = $phase:ident;
        direction = $direction:ident;
        ids = [ $( $min_version:expr => $id:expr ),* $(,)? ];
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, PartialEq)]
        pub struct $name {
            $(
                $(#[$field_meta])*
                pub $field : $field_ty,
            )*
        }

        impl $crate::packet::Packet for $name {
            const NAME: &'static str = stringify!($name);
            const PHASE: $crate::packet::Phase = $crate::packet::Phase::$phase;
            const DIRECTION: $crate::packet::Direction =
                $crate::packet::Direction::$direction;

            fn id(version: $crate::version::ProtocolVersion) -> Option<i32> {
                $(
                    if version.at_least($min_version) {
                        return Some($id);
                    }
                )*
                None
            }

            fn decode(
                reader: &mut $crate::wire::Reader<'_>,
                version: $crate::version::ProtocolVersion,
            ) -> $crate::error::Result<Self> {
                // Packets without version-dependent fields do not read `version`, and packets
                // without any fields do not read at all.
                let _ = &version;
                $(
                    let $field: $field_ty = $crate::packet_read_field!(
                        reader, version, $field_ty, stringify!($field) $(, $feature)?
                    );
                )*
                let packet = Self { $( $field, )* };
                reader.finish(<Self as $crate::packet::Packet>::NAME)?;
                Ok(packet)
            }

            fn encode(
                &self,
                writer: &mut $crate::wire::Writer<'_>,
                version: $crate::version::ProtocolVersion,
            ) -> $crate::error::Result<()> {
                let _ = (&version, &writer);
                $(
                    $crate::packet_write_field!(
                        writer,
                        version,
                        self.$field,
                        $field_ty,
                        <Self as $crate::packet::Packet>::NAME,
                        stringify!($field)
                        $(, $feature)?
                    );
                )*
                Ok(())
            }
        }
    };
}

/// Internal helper of [`packet!`](crate::packet!): reads one field, gated or not.
#[doc(hidden)]
#[macro_export]
macro_rules! packet_read_field {
    ($reader:expr, $version:expr, $ty:ty, $field:expr) => {
        <$ty as $crate::wire::Wire>::read($reader, $version, $field)?
    };
    ($reader:expr, $version:expr, $ty:ty, $field:expr, $feature:ident) => {
        $crate::packet::read_since(
            $reader,
            $version,
            $crate::version::Feature::$feature,
            $field,
        )?
    };
}

/// Internal helper of [`packet!`](crate::packet!): writes one field, gated or not.
#[doc(hidden)]
#[macro_export]
macro_rules! packet_write_field {
    ($writer:expr, $version:expr, $value:expr, $ty:ty, $packet:expr, $field:expr) => {
        <$ty as $crate::wire::Wire>::write(&$value, $writer, $version)
    };
    ($writer:expr, $version:expr, $value:expr, $ty:ty, $packet:expr, $field:expr, $feature:ident) => {
        $crate::packet::write_since(
            $writer,
            $version,
            &$value,
            $crate::version::Feature::$feature,
            $packet,
            $field,
        )?
    };
}
