# Server rund on minecraft default port
address: "0.0.0.0:25565"

# The global timeout and rate limiter configuration. By default, allowing 60 requests per minute where
# each request may take up to 120 seconds to complete. Otherwise, the client will be timed out.
timeout: 120
rate_limiter:
  duration: 60
  limit: 60

# The set of routes that Passage handles. The route hostname is matched unsing a regex and may contain
# appropriate wildcards.
routes:
- hostname: "mc.example.net"
  # The status adapter used for getting the server status.
  status:
    type: http
    address: "https://example.net/status"
    cache_duration: 30
  # The authentication used to authenticate the client. By default, it uses the standard Mojang API.
  authentication:
    type: mojang
    server_id: ""
  # The discovery adapter used to find the server to connect to.
  discovery:
    type: dns
    domain: "servers.example.net"
    # Any custom actions that further influence the discovery. At the end, the first server in
    # the list of discovered servers is selected. The actions may filter or reorder the servers
    # such that a different server is selected. They may also be used for other purposes such as
    # sending notifications. The name is optional for improved logging.
    actions:
    # Next, the servers are filtered to only include those that are online.
    - type: filter
      name: "server-filter"
      rules:
      - op: "equals"
        field: "status"
        value: "online"
    # Next, the servers are passed to an gRPC adapter that may alter the servers in any way. This
    # could further filter the servers, inject additional information, or reorder them.
    - type: grpc
      name: "example-interceptor"
      address: "127.0.0.1:50051"
    # Lastly, the servers are sorted such that the fullest server with space remaining is selected.
    # In case there are multiple such servers, it selects a random one. This allows for incremental
    # ordering of servers.
    - type: player_fill
      name: "player-fill-strategy"
    - type: random
      name: "random-strategy"
