# yaml-language-server: $schema=./schema.json

# Passage runs on the default Minecraft port.
address: "0.0.0.0:25565"

# The global timeout and rate limiter configuration. By default, allowing 60 connections per minute
# per IP, where each connection may take up to 120 seconds to complete. Otherwise, the client is
# timed out. The rate limiter is disabled unless this section is present.
timeout: 120
rate_limiter:
  duration: 60
  limit: 60

# The set of routes that Passage handles. The route hostname is matched using a regex and may contain
# appropriate wildcards. The first matching route wins.
routes:
- hostname: "mc.example.net"
  # The status adapter used for getting the server status.
  status:
    type: http
    address: "https://example.net/status"
    cache_duration: 30
  # The authentication used to authenticate the client. By default, it uses the standard Mojang API.
  authentication:
    type: mojang
    server_id: ""
  # The discovery adapter used to find the server to connect to.
  discovery:
    type: dns_discovery
    domain: "servers.example.net"
    record_type: srv
    # Any custom actions that further influence the discovery. At the end, the first server in
    # the list of discovered servers is selected. The actions may filter or reorder the servers
    # such that a different server is selected. They may also be used for other purposes such as
    # sending notifications.
    actions:
    # First, the servers are filtered to only include those that are online.
    - type: meta_filter
      rules:
      - op: "equals"
        key: "status"
        value: "online"
    # Next, the servers are passed to a gRPC adapter that may alter the servers in any way. This
    # could further filter the servers, inject additional information, or reorder them.
    - type: grpc
      address: "http://127.0.0.1:50051"
    # Lastly, the servers are sorted such that the fullest server with space remaining ends up first
    # and is therefore selected. This allows for incremental filling of servers. The `field` names
    # the target metadata key holding the current player count.
    - type: player_fill_strategy
      field: "players"
      max_players: 50
